---

- name: copy of the manifests kubernetes to the master node 
  hosts: master-node
  tasks: 
  - name: copy docker composer file to node
    copy: 
      src: ../kubernetes/
      dest: /root/kubernetes/
    become: yes

  - name: deploy the database
    command: "kubectl apply -f /root/kubernetes/database.yml"

  - name: deploy the backend app
    command: "kubectl apply -f /root/kubernetes/backend.yml"

  - name: deploy the frontend app
    command: "kubectl apply -f /root/kubernetes/frontend.yml"

    
